---
language: go
go:
  - 1.8.x

install:
  - go get github.com/mattn/goveralls
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
